from django.apps import AppConfig

# ProjectsConfig class is autogenerated by Django when you create a new app with startapp.
class ProjectsConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'projects'
