# Generated by Django 5.0.3 on 2024-07-31 01:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_profile_username"),
    ]

    operations = []
