# Generated by Django 5.0.3 on 2024-07-30 06:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_project_featured_image"),
    ]

    operations = []
