# Generated by Django 5.0.3 on 2024-07-30 06:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_rename_source_line_to_source_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="source_line",
            new_name="source_link",
        ),
    ]
