# Generated by Django 5.0.3 on 2024-08-08 14:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0009_auto_20240808_1403"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="text",
            new_name="body",
        ),
    ]
