# Generated by Django 5.0.3 on 2024-08-08 14:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0011_auto_20240808_1407"),
    ]

    operations = []
